### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by amirouche** [amirouche/nomunofu#1]
- [ ] Server: stream decompression of `latest-all.nt.gz`
- [ ] Server: Accept pattern-matching queries
- [ ] Client: Python API
